# Generated by Django 4.1.7 on 2023-03-02 15:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Название дерева"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Текстовый id")),
            ],
            options={
                "verbose_name": "Дерево",
                "verbose_name_plural": "Деревья",
            },
        ),
    ]
