# Generated by Django 4.1.7 on 2023-03-02 17:43
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "to",
                    models.URLField(
                        help_text="URL полный или относительный или имя в роутах джанго",
                        unique=True,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(default=0, verbose_name="Сортировка"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.treeitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ветка дерева",
                "verbose_name_plural": "Ветки деревьев",
            },
        ),
    ]
