# Generated by Django 4.1.7 on 2023-03-02 18:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_treeitem_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="treeitem",
            options={
                "ordering": ["parent"],
                "verbose_name": "Ветка дерева",
                "verbose_name_plural": "Ветки деревьев",
            },
        ),
    ]
