# Generated by Django 4.1.7 on 2023-03-02 18:08
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_treeitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treeitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.treeitem",
            ),
        ),
    ]
