# Generated by Django 4.1.7 on 2023-03-02 18:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_treeitem_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="treeitem",
            options={
                "ordering": ["order_index"],
                "verbose_name": "Ветка дерева",
                "verbose_name_plural": "Ветки деревьев",
            },
        ),
        migrations.AlterField(
            model_name="treeitem",
            name="to",
            field=models.CharField(
                help_text="URL полный или относительный или имя в роутах джанго",
                max_length=128,
                unique=True,
                verbose_name="Ссылка",
            ),
        ),
    ]
